### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by ylluminate** [siuying/charlock_holmes-jruby#1]
I was curious @siuying and @webandtech as to what it would take to get this inline with a more current release of the parent version.  For example, right now GitLab is asking for v0.6.9.4 of the gem and of course this hasn't been updated for quite some time so I'd like to reconcile what's going on here and perhaps what needs to be done.

**Comment by siuying** [comment]
Maybe you can help and send a pull request? :-)

**Comment by ylluminate** [comment]
Perhaps so.  Right now I'm tied up in quite a bit and I'm not sure what kind of time investment this might take.  I suspect (I've not read your initial commits) that it might be more prudent to simply take the current `charlock_holmes` base and just redo the initial steps you performed to make this work in the first place vs starting from your current base and bringing it up.

**Comment by siuying** [comment]
Sounds good :+1:
